### ISSUE TITLE
metafile gunzip depends on Blob#stream, which jsdom does not implement

### ISSUE THREAD

**Issue by tokg-venv** [genspark-ai/genoffice#798]
## App

Shared engine package `packages/docx-engine`; the failure surfaces in every app whose
tests run under jsdom (slides, docs, pdf, markdown, html).

## Version and OS

`main` @ `3f9d07d`; platform-independent (the trigger is the test environment, not the OS).

## What happened?

`packages/docx-engine/src/metafile.ts:34` — `gunzip()` inflates gzip-compressed metafiles
(`.emz` / `.wmz`) under a 64 MB cap, so a decompression bomb cannot exhaust renderer memory
during conversion (the cap came in with #755). It feeds the bytes to
`DecompressionStream('gzip')` through `new Blob([bytes]).stream()`.

`Blob.prototype.stream` is not universally available. jsdom — the environment the slides,
docs, pdf, markdown and html app tests run in — ships a `Blob` with no `stream()` (its
`ReadableStream` is Node's, so streams themselves are fine). Where that is the case:

```ts
const reader = new Blob([new Uint8Array(bytes)])
  .stream()          // TypeError: (intermediate value).stream is not a function
  .pipeThrough(new DecompressionStream('gzip'))
  .getReader()
```

The `try/catch` in `metafileToDataUrl` (`metafile.ts:108`) swallows that into a
`console.warn` and a `null` return, so the image **silently renders as an empty frame** —
it looks like an unsupported format rather than a broken code path.

**Expected:** a gzipped metafile decodes the same way in every environment the package runs
in, and the 64 MB cap is exercised in the renderer-like environment it exists to protect.

**Why nothing catches it today:**

- the metafile tests live in `packages/docx-engine`, whose vitest environment is `node`,
  where `Blob#stream` exists;
- the only jsdom-environment test that touches this module
  (`apps/slides/tests/image-loader.test.ts:5`) mocks `@genoffice/docx-engine/metafile`
  wholesale, so `gunzip` never runs;
- real browsers and Node both have `Blob#stream`, so production is unaffected. This is a
  test-environment landmine, not a live bomb: it throws before anything is allocated.

**Impact**

1. The first real jsdom test that decodes an `.emz` gets a confusing `TypeError`, or worse,
   a silently empty image that reads as "format unsupported".
2. The cap whose comment says *"must not exhaust renderer memory"* cannot be tested in the
   renderer-ish environment it was written for — `MAX_METAFILE_GUNZIP_BYTES` is currently
   only covered in a Node environment.

## Logs / screenshots

Reproduced by calling `gunzip` with `Blob.prototype.stream` removed (jsdom behaves the same):

```
TypeError: (intermediate value).stream is not a function
 ❯ gunzip packages/docx-engine/src/metafile.ts:36:6
 ❯ metafileToDataUrl packages/docx-engine/src/metafile.ts:91:26

metafileToDataUrl: conversion failed (image/x-emz): TypeError: ...
```

## Related

The same pattern is what failed 389 `apps/docs` tests in #781: `zip-load.ts` inflated through
`Blob#stream` and every `parseDocx` in that jsdom suite threw. That PR fixed it by building
the stream by hand, keeping the helper local to `zip-load.ts`. This issue is about
`metafile.ts`, and about giving both call sites one home instead of two copies.

## Proposed fix

Add a small `streamBytes()` helper — a `ReadableStream` over bytes already in memory, fed
in 64 KiB slices — in its own module with no Node builtins (so it stays bundleable into the
renderer), have `metafile.ts` inflate through it, and add a test that runs `gunzip` with
`Blob.prototype.stream` deleted so the dependency cannot come back unnoticed.
